export const MILLISECONDS_PER_SECOND = 1000;
export const SECONDS_PER_MINUTE = 60;
export const MINUTES_PER_HOUR = 60;
export const HOURS_PER_DAY = 24;
export const DAYS_PER_WEEK = 7;

export const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * SECONDS_PER_MINUTE;
export const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_MINUTE * MINUTES_PER_HOUR;
export const MILLISECONDS_PER_DAY = MILLISECONDS_PER_HOUR * HOURS_PER_DAY;

export const TOKEN_EXPIRY_MS = 15 * MILLISECONDS_PER_MINUTE;
export const REFRESH_TOKEN_EXPIRY_MS = 7 * MILLISECONDS_PER_DAY;
export const PASSWORD_RESET_EXPIRY_MS = 1 * MILLISECONDS_PER_HOUR;

export const RATE_LIMIT_WINDOW_MS = 15 * MILLISECONDS_PER_MINUTE;
export const AUTH_RATE_LIMIT_MAX_ATTEMPTS = 5;
