export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 128;
export const NAME_MIN_LENGTH = 2;
export const NAME_MAX_LENGTH = 100;
export const EMAIL_MAX_LENGTH = 255;
export const NOTES_MAX_LENGTH = 1000;

export const VALIDATION = {
  NAME: { MIN: NAME_MIN_LENGTH, MAX: NAME_MAX_LENGTH },
  EMAIL: { MAX: EMAIL_MAX_LENGTH },
  PASSWORD: { MIN: PASSWORD_MIN_LENGTH, MAX: PASSWORD_MAX_LENGTH },
  NOTES: { MAX: NOTES_MAX_LENGTH },
  ADDRESS: { MAX: 200 },
  DESCRIPTION: { MAX: 500 },
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

export const RATE_LIMIT = {
  WINDOW_MS: 15 * 60 * 1000,
  CONTACT_MAX: 3,
  AUTH_MAX: 5,
  PASSWORD_RESET_MAX: 3,
  API_MAX: 100,
  REFRESH_MAX: 10,
};

export const DATABASE = {
  MAX_RETRIES: 3,
  RETRY_DELAY_MS: 1000,
  CONNECTION_TIMEOUT_MS: 30000,
  SOCKET_TIMEOUT_MS: 45000,
  MAX_RETRY_DELAY_MS: 10000,
};
