export const ErrorCodes = {
  // Authentication
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',

  // Validation
  VAL_INVALID_INPUT: 'VAL_INVALID_INPUT',
  VAL_REQUIRED_FIELD: 'VAL_REQUIRED_FIELD',
  VAL_INVALID_ID: 'VAL_INVALID_ID',
  VAL_INVALID_EMAIL: 'VAL_INVALID_EMAIL',

  // Resource
  RES_NOT_FOUND: 'RES_NOT_FOUND',
  RES_CONFLICT: 'RES_CONFLICT',
  RES_ALREADY_EXISTS: 'RES_ALREADY_EXISTS',

  // Permission
  PERM_FORBIDDEN: 'PERM_FORBIDDEN',
  PERM_INSUFFICIENT: 'PERM_INSUFFICIENT',

  // Business Logic
  BIZ_OPERATION_FAILED: 'BIZ_OPERATION_FAILED',
  BIZ_INVALID_STATUS: 'BIZ_INVALID_STATUS',

  // System
  SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
  SYS_DATABASE_ERROR: 'SYS_DATABASE_ERROR',
  SYS_RATE_LIMIT_EXCEEDED: 'SYS_RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
